### ISSUE TITLE
Send a message without id

### ISSUE THREAD

**Issue by joaosalvadoMicrosoft** [microsoft/kafka-connect-cosmosdb#144]
we are trying to send a kafka message to topic and use the connect to send the message to cosmos.
This works but only if we explicitly set the variable 'id' is there any way to mapping this ?

**Comment by ryancrawcour** [comment]
this should work with the use of Connect Converters. we should test this before we look to address in this connector specifically.

**Comment by ryancrawcour** [comment]
From the [KIP](https://cwiki.apache.org/confluence/display/KAFKA/KIP-66%3A+Single+Message+Transforms+for+Kafka+Connect)

_The framework for Single Message Transforms was released on 0.10.2.0 but only some of the built-in transformations were included with that version. The table below indicates what version each transformation was or will be released with. A few don't have the exact name as listed in the KIP because they were found to be slightly inaccurate during code review_


Transformation | Version
-- | --
InsertField | 0.10.2.0
ReplaceField | 0.10.2.0
MaskField | 0.10.2.0
ValueToKey | 0.10.2.0
HoistField | 0.10.2.0
ExtractField | 0.10.2.0
SetSchemaMetadata | 0.10.2.0
TimestampRouter | 0.10.2.0
RegexRouter | 0.10.2.0
Flatten | 0.11.0.0
Cast | 0.11.0.0
TimestampConverter | 0.11.0.0

The [Kafka documentation](http://kafka.apache.org/documentation.html) also includes references for each transformation.

**Comment by ryancrawcour** [comment]
Things to test to verifying if SMT will suffice 
- _InsertField_, what happens if the field already exists? do you end up with malformed / invalid json? 
- _ReplaceField_, what happens if the field doesn't exist? is an exception thrown?

**Comment by ryancrawcour** [comment]
NOTE: SMTs can be chained together. So let's say you wanted to create an id field from root/person/id you could first run an _ExtractField_ SMT to extract the value of root/person/id and then chain on the _InsertField_ SMT to insert a new field called id with that value.

**Comment by ryancrawcour** [comment]
what if i wanted to _InsertField_ of a new UUID?

**Comment by ryancrawcour** [comment]
[Kafka Connect SMT to add a random UUID] (https://github.com/confluentinc/kafka-connect-insert-uuid)

**Comment by ryancrawcour** [comment]
The InsertField SMT will throw an exception if the id field already exists in the document. 
So, if we're going to use this, we might need to include a Predicate

_##Predicates
Transformations can be configured with predicates so that the transformation is applied only to records which satisfy a condition. You can use predicates in a transformation chain and, when combined with the Apache Kafka® Filter, predicates can conditionally filter out specific records._

[Predicates](https://docs.confluent.io/platform/current/connect/transforms/filter-ak.html#filter-predicates)

**Comment by sivamu** [comment]
Rather than doing this through a SMT, we've decided to add the code within the connector itself, since the ID field for cosmos is a common need. Will also need a Sink setting to enable/disable creating the ID if it doesn't exist.

**Comment by sivamu** [comment]
To use predicates to check if a field exists and based on that condition to apply the SMT, is something that does not work natively with Kafka. We will need to code our own Predicate to support such behavior and this will be added beyond M1 ([reference](https://twitter.com/ryancrawcour/status/1339471376848056320)).

Currently, will be just documenting the simple use case with the SMT.
