### ISSUE TITLE
Source connector needs to be able to support Converters

### ISSUE THREAD

**Issue by ryancrawcour** [microsoft/kafka-connect-cosmosdb#194]
Source connector needs to be able to support Converters so that we can support JSON (string without a schema) as we do today, but also JSON with a schema, and AVRO.

Add a test to ensure that when the connector is configured with avro and json-schema converters it works as expected.

**Comment by ryancrawcour** [comment]
Additional info about Connect Converters - https://www.confluent.io/blog/kafka-connect-deep-dive-converters-serialization-explained/

**Comment by kev-ms** [comment]
There is a need of JSON to Schema and Struct conversion of source record in order for converters to successfully work with schema enabled JSON Converter and Confluent AVRO Converter

Ref documents: 
https://cwiki.apache.org/confluence/display/KAFKA/KIP-301%3A+Schema+Inferencing+for+JsonConverter
https://stackoverflow.com/questions/44649913/is-complex-or-nested-json-schema-supported-by-confluent-kafka-connect
https://docs.confluent.io/platform/current/schema-registry/serdes-develop/serdes-json.html#test-drive-json-schema

**Comment by kev-ms** [comment]
https://downloads.apache.org/kafka/2.3.0/javadoc/index.html?org/apache/kafka/connect/data/Struct.html

**Comment by kev-ms** [comment]
Noticed connect exception when avro converter is configured and passed nested JSON object.

`Caused by: org.apache.kafka.common.errors.SerializationException: Error serializing Avro message
Caused by: org.apache.avro.SchemaParseException: Can't redefine: io.confluent.connect.avro.ConnectDefault
        at org.apache.avro.Schema$Names.put(Schema.java:1511)
        at org.apache.avro.Schema$NamedSchema.writeNameRef(Schema.java:782)
        at org.apache.avro.Schema$RecordSchema.toJson(Schema.java:943)
        at org.apache.avro.Schema$RecordSchema.fieldsToJson(Schema.java:971)
        at org.apache.avro.Schema$RecordSchema.toJson(Schema.java:955)
        at org.apache.avro.Schemas.toString(Schemas.java:46)
        at org.apache.avro.Schemas.toString(Schemas.java:30)`

Based on [AvroData](https://github.com/confluentinc/schema-registry/blob/master/avro-data/src/main/java/io/confluent/connect/avro/AvroData.java) schema name defaults to `ConnectDefault` if not provided.

Solution: Generate unique shcema name for each struct for nested JSON record
