### ISSUE TITLE
Possible duplicate/erroneous configs

### ISSUE THREAD

**Issue by brandynbrown** [microsoft/kafka-connect-cosmosdb#277]
Please document the difference between the following configs or remove if erroneous/duplicate:

- topic-container map & cosmos container name? 
- Cosmos Assigned Container & Cosmos worker name

Please document findings as a topic for discussion on the board.

**Comment by kev-ms** [comment]
- Container lists are avoidable by abstracting list of containers map.
- Couldn't validate use of assigned container and worker name. Verify with cosmos db team to get more details on these config values

**Comment by sivamu** [comment]
I agree with the container list, don't think it's needed since we have the same info defined in the topic-container map. Assigned container is needed so that each tasks can monitor it's own container if we setup a connector to monitor multiple cosmos collections. BUT I am not sure if assigned container needs to be displayed as a config for the user, since it's essentially used internally. 

I think with the new configs needed for the changefeedprocessor in #309, worker name will come in handy. Then again, I don't know if this is a setting that the user should bother with.

**Comment by kev-ms** [comment]
Team will revisit this once making new changes with multiple source workers.

**Comment by brandynbrown** [comment]
blocked by #309

**Comment by ryancrawcour** [comment]
how is this blocked by #309? config changes should be separate from the balancing across multiple workers.

**Comment by sivamu** [comment]
I think the worker name and container name configs will be used to set the leasePrefix needed for #309. We can then trim out any unneeded configs after completing that issue.
