### ISSUE TITLE
SIGSEGV with Confluent Platform 6.0.2

### ISSUE THREAD

**Issue by vdesabou** [microsoft/kafka-connect-cosmosdb#379]
## Description

Using `1.0.4-beta`, I'm experiencing a SIGSEGV in the connect worker when using the source and sink connector with Confluent Platform 6.0.2 (Docker image based on `confluentinc/cp-server-connect-base:6.0.2`)
My test is [here](https://github.com/vdesabou/kafka-docker-playground/blob/master/connect/connect-azure-cosmosdb-source/azure-cosmosdb-source.sh) and the exact same test with Confluent Platform 6.1.1 works fine (see results of my CI [here](https://github.com/vdesabou/kafka-docker-playground/issues/846))

The stack trace in connect worker is:

```
[2021-04-16 16:05:06,889] INFO Creating Cosmos Client. (com.azure.cosmos.kafka.connect.source.CosmosDBSourceTask)
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f914076dc80, pid=1, tid=160
#
# JRE version: OpenJDK Runtime Environment Zulu11.45+27-CA (11.0.10+9) (build 11.0.10+9-LTS)
# Java VM: OpenJDK 64-Bit Server VM Zulu11.45+27-CA (11.0.10+9-LTS, mixed mode, tiered, compressed oops, g1 gc, linux-amd64)
# Problematic frame:
# C  0x00007f914076dc80
#
# No core dump will be written. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /home/appuser/hs_err_pid1.log
#
# If you would like to submit a bug report, please visit:
#   http://www.azulsystems.com/support/
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
[error occurred during error reporting (), id 0xb, SIGSEGV (0xb) at pc=0x00007f91f2dded21]
```

[hs_err_pid1.log](https://github.com/microsoft/kafka-connect-cosmosdb/files/6349694/hs_err_pid1.log)

## Expected Behavior

No SIGSEV error

## Reproduce

1. git clone https://github.com/vdesabou/kafka-docker-playground.git
2. cd connect/connect-azure-cosmosdb-source
3. ./azure-cosmosdb-source.sh
4. See error in `connect` container `docker container logs connect`

## Additional Context

This issue is 100% reproducible

**Comment by ryancrawcour** [comment]
thanks for raising this issue. will take a look at it.

**Comment by ryancrawcour** [comment]
I did some investigation on this issue and found that “io.netty.internal.tcnative.SSL” is unable to get initialized. Attached log file for the same. It seems this issue could be addressed like mentioned in this link.
 
https://github.com/GoogleCloudPlatform/pubsub/issues/215
 
JVM Fatal error log file : 
![1](https://user-images.githubusercontent.com/38923605/117233393-2335c600-ae77-11eb-89a3-8c2eb5f2c801.jpg)

Actual Error : 
![2](https://user-images.githubusercontent.com/38923605/117233398-24ff8980-ae77-11eb-8c9c-39c715d3ce0c.jpg)

**Comment by ryancrawcour** [comment]
08:24:57,734] DEBUG Failed to load netty-tcnative; OpenSslEngine will be unavailable, unless the application has already loaded the symbols by some other means. See
https://netty.io/wiki/forked-tomcat-native.html for more information. (io.netty.handler.ssl.OpenSsl)
 
2java.lang.IllegalArgumentException: Failed to load any of the given libraries: [netty_tcnative_linux_x86_64_fedora, netty_tcnative_linux_x86_64, netty_tcnative_x86_64, netty_tcnative]
 
3 at io.netty.util.internal.NativeLibraryLoader.loadFirstAvailable(NativeLibraryLoader.java:104)
 
4 at io.netty.handler.ssl.OpenSsl.loadTcNative(OpenSsl.java:581)
 
5 at io.netty.handler.ssl.OpenSsl.<clinit>(OpenSsl.java:133)
 
6 at reactor.netty.tcp.SslProvider.updateDefaultConfiguration(SslProvider.java:388)
 
7 at reactor.netty.tcp.SslProvider.<init>(SslProvider.java:309)
 
8 at reactor.netty.tcp.SslProvider$Build.build(SslProvider.java:569)
 
9 at reactor.netty.tcp.TcpClientSecure.<clinit>(TcpClientSecure.java:71)
 
10 at reactor.netty.tcp.SslProvider.defaultClientProvider(SslProvider.java:100)
 
11 at reactor.netty.http.client.HttpClientSecure.<clinit>(HttpClientSecure.java:72)
 
12 at reactor.netty.http.client.HttpClientConnect$MonoHttpConnect.lambda$subscribe$0(HttpClientConnect.java:301)
 
13 at reactor.core.publisher.MonoCreate.subscribe(MonoCreate.java:57)
 
14 at reactor.core.publisher.FluxRetryPredicate$RetryPredicateSubscriber.resubscribe(FluxRetryPredicate.java:124)
 
15 at reactor.core.publisher.MonoRetryPredicate.subscribeOrReturn(MonoRetryPredicate.java:51)
 
16 at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:57)
 
17 at reactor.netty.http.client.HttpClientConnect$MonoHttpConnect.subscribe(HttpClientConnect.java:326)
 
18 at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64)
 
19 at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52)
 
20 at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64)
 
21 at reactor.core.publisher.MonoDelaySubscription.accept(MonoDelaySubscription.java:52)
 
22 at reactor.core.publisher.MonoDelaySubscription.accept(MonoDelaySubscription.java:33)
 
23 at reactor.core.publisher.FluxDelaySubscription$DelaySubscriptionOtherSubscriber.onNext(FluxDelaySubscription.java:123)
 
24 at reactor.core.publisher.MonoDelay$MonoDelayRunnable.run(MonoDelay.java:117)
 
25 at 
reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:68)
 
26 at 
reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:28)
 
27 at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
 
28 at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
 
29 at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
 
30 at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
 
31 at java.base/java.lang.Thread.run(Thread.java:834)
 
32 Suppressed: java.lang.UnsatisfiedLinkError: could not load a native library: netty_tcnative_linux_x86_64_fedora
 
33 at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:226)
 
34 at io.netty.util.internal.NativeLibraryLoader.loadFirstAvailable(NativeLibraryLoader.java:96)
 
35 ... 28 more
36 Caused by: java.io.FileNotFoundException: META-INF/native/libnetty_tcnative_linux_x86_64_fedora.so
 
37 at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:175)
 
38 ... 29 more
39 Suppressed: java.lang.UnsatisfiedLinkError: no netty_tcnative_linux_x86_64_fedora in java.library.path: [/usr/java/packages/lib, /usr/lib64, /lib64, /lib, /usr/lib]
 
40 at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2670)
 
41 at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:830)
 
42 at java.base/java.lang.System.loadLibrary(System.java:1873)
 
43 at io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:38)
 
44 at io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:351)
 
45 at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:136)
 
46 ... 29 more
47 Suppressed: java.lang.UnsatisfiedLinkError: no netty_tcnative_linux_x86_64_fedora in java.library.path: [/usr/java/packages/lib, /usr/lib64, /lib64, /lib, /usr/lib]
 
48 at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2670)
 
49 at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:830)
 
50 at java.base/java.lang.System.loadLibrary(System.java:1873)
 
51 at io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:38)
 
52 at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 
53 at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
 
54 at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 
55 at java.base/java.lang.reflect.Method.invoke(Method.java:566)
 
56 at io.netty.util.internal.NativeLibraryLoader$1.run(NativeLibraryLoader.java:371)
 
57 at java.base/java.security.AccessController.doPrivileged(Native Method)
 
58 at io.netty.util.internal.NativeLibraryLoader.loadLibraryByHelper(NativeLibraryLoader.java:363)
 
59 at io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:341)
 
60 ... 30 more
61 Suppressed: java.lang.NoSuchMethodError: Method io.netty.internal.tcnative.NativeStaticallyReferencedJniMethods.sslSessCacheClient()I not found
 
62 at java.base/java.lang.ClassLoader$NativeLibrary.load0(Native Method) 
63 at java.base/java.lang.ClassLoader$NativeLibrary.load(ClassLoader.java:2442)
 
64 at java.base/java.lang.ClassLoader$NativeLibrary.loadLibrary(ClassLoader.java:2498)
 
65 at java.base/java.lang.ClassLoader.loadLibrary0(ClassLoader.java:2694)
 
66 at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2627)
 
67 at java.base/java.lang.Runtime.load0(Runtime.java:768)
 
68 at java.base/java.lang.System.load(System.java:1837)
 
69 at io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:36)
 
70 at io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:351)
 
71 at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:205)
 
72 at io.netty.util.internal.NativeLibraryLoader.loadFirstAvailable(NativeLibraryLoader.java:96)
 
73 ... 28 more
74 Suppressed: java.lang.UnsatisfiedLinkError: could not load a native library: netty_tcnative_x86_64
 
75 at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:226)
 
76 at io.netty.util.internal.NativeLibraryLoader.loadFirstAvailable(NativeLibraryLoader.java:96)
 
77 ... 28 more
78 Caused by: java.io.FileNotFoundException: META-INF/native/libnetty_tcnative_x86_64.so
 
79 at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:175)
 
80 ... 29 more
81 Suppressed: java.lang.UnsatisfiedLinkError: no netty_tcnative_x86_64 in java.library.path: [/usr/java/packages/lib, /usr/lib64, /lib64, /lib, /usr/lib]
 
82 at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2670)
 
83 at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:830)
 
84 at java.base/java.lang.System.loadLibrary(System.java:1873)
 
85 at io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:38)
 
86 at io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:351)
 
87 at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:136)
 
88 ... 29 more
89 Suppressed: java.lang.UnsatisfiedLinkError: no netty_tcnative_x86_64 in java.library.path: [/usr/java/packages/lib, /usr/lib64, /lib64, /lib, /usr/lib]
 
90 at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2670)
 
91 at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:830)
 
92 at java.base/java.lang.System.loadLibrary(System.java:1873)
 
93 at io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:38)
 
94 at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 
95 at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
 
96 at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 
97 at java.base/java.lang.reflect.Method.invoke(Method.java:566)
 
98 at io.netty.util.internal.NativeLibraryLoader$1.run(NativeLibraryLoader.java:371)
 
99 at java.base/java.security.AccessController.doPrivileged(Native Method)
 
100 at io.netty.util.internal.NativeLibraryLoader.loadLibraryByHelper(NativeLibraryLoader.java:363)
 
101 at io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:341)
 
102 ... 30 more
103 Suppressed: java.lang.UnsatisfiedLinkError: could not load a native library: netty_tcnative
 
104 at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:226)
 
105 at io.netty.util.internal.NativeLibraryLoader.loadFirstAvailable(NativeLibraryLoader.java:96)
 
106 ... 28 more
107 Caused by: java.io.FileNotFoundException: META-INF/native/libnetty_tcnative.so
 
108 at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:175)
 
109 ... 29 more
110 Suppressed: java.lang.UnsatisfiedLinkError: no netty_tcnative in java.library.path: [/usr/java/packages/lib, /usr/lib64, /lib64, /lib, /usr/lib]
 
111 at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2670)
 
112 at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:830)
 
113 at java.base/java.lang.System.loadLibrary(System.java:1873)
 
114 at io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:38)
 
115 at io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:351)
 
116 at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:136)
 
117 ... 29 more
118 Suppressed: java.lang.UnsatisfiedLinkError: no netty_tcnative in java.library.path: [/usr/java/packages/lib, /usr/lib64, /lib64, /lib, /usr/lib]
 
119 at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2670)
 
120 at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:830)
 
121 at java.base/java.lang.System.loadLibrary(System.java:1873)
 
122 at io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:38)
 
123 at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 
124 at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
 
125 at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 
126 at java.base/java.lang.reflect.Method.invoke(Method.java:566)
 
127 at io.netty.util.internal.NativeLibraryLoader$1.run(NativeLibraryLoader.java:371)
 
128 at java.base/java.security.AccessController.doPrivileged(Native Method)
 
129 at io.netty.util.internal.NativeLibraryLoader.loadLibraryByHelper(NativeLibraryLoader.java:363)
 
130 at io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:341)
 
131 ... 30 more
132[2021-02-15 08:24:57,738] DEBUG Initialize netty-tcnative using engine: 'default' (io.netty.handler.ssl.OpenSsl)
 
133#
134# A fatal error has been detected by the Java Runtime Environment: 
135#
136# SIGSEGV (0xb) at pc=0x00007f6637bed450, pid=1, tid=163 
I have tested with:
-Docker image based on cp-server-connect-base:6.1.0
-On Mac OS with CP 6.1.0 ZIP installation
This only happens with CP 6.1.0

**Comment by vdesabou** [comment]
Hi @ryancrawcour 

Thank you for your analysis.
FYI, we (I work for Confluent) have exactly the same issue with Confluent Azure blob storage source connector. I tried to summarise the different issues with this table:

![image](https://user-images.githubusercontent.com/4061923/117474767-90bb2280-af5b-11eb-8c1b-c68807d27118.png)

With CP 6.0.2, if I replace existing `/usr/share/java/confluent-security/connect/netty-tcnative-boringssl-static-2.0.30.Final.jar` with `netty-tcnative-boringssl-static-2.0.34.Final.jar` using:

```
  connect:
    volumes:
      - ../../connect/connect-azure-blob-storage-source/netty-tcnative-boringssl-static-2.0.34.Final.jar:/usr/share/java/confluent-security/connect/netty-tcnative-boringssl-static-2.0.30.Final.jar
```

Then it works..

So it is really an issue with CP 6.0.2, I think you can close this ticket

**Comment by ryancrawcour** [comment]
As agreed with @vdesabou we won't be looking at this issue at this time.
